### ISSUE TITLE
Scripts: setup travis to support multiple different builds

### ISSUE THREAD

**Issue by midenok** [tempesta-tech/mariadb#72]
Use [this](https://docs.travis-ci.com/user/speeding-up-the-build/#Parallelizing-your-builds-across-virtual-machines) technique to do 2 diffent builds:

1. debug build (the same as of now);
2.  production build.

**Comment by kevgs** [comment]
Why not just run two different build sequentially? It looks simpler.

**Comment by kevgs** [comment]
Build matrix is about paralellization. It's possible to run two builds if we create two folders, run cmake in both of them and then run compilation. I don't know whether we will have a performance gain in this case.

**Comment by midenok** [comment]
Pls, paste here config for parallel build and config for sequential build.

**Comment by kevgs** [comment]
This is sequential build. Difference is in `script`.

``` yml
# vim ft=yaml
# travis-ci.org definition

branches:
  only:
    - natsys/trunk

# non-container builds don't have enough RAM to reliably compile
sudo: required
dist: trusty

language: cpp
compiler:
  - gcc
#  - clang # See commit f38808 if you want to re-enable clang builds
cache:
  apt:
  ccache:

# Timing on build an test needs to be < 50 minutes. The compile is ~4-5minutes
# so here we group the tests such that this happens.

addons:
  apt:
    packages: # make sure these match debian/control contents
      - bison
      - chrpath
      - cmake
      - debhelper
      - dh-apparmor
      - dpatch
      - libaio-dev
      - libboost-dev
      - libjudy-dev
      - libncurses5-dev
      - libpam0g-dev
      - libreadline-gplv2-dev
      - libssl-dev
      - lsb-release
      - perl
      - po-debconf
      - psmisc
      - zlib1g-dev
      - libcrack2-dev # no effect as the package is disallowed on Travis-CI
      - libjemalloc-dev
      - devscripts # implicit for any build on Ubuntu
      - libtcmalloc-minimal4

script:
  - ${CC} --version ; ${CXX} --version
  - cd "${TRAVIS_BUILD_DIR}"
  - mkdir DEBUG
  - mkdir RELEASE
  - cd "${TRAVIS_BUILD_DIR}/DEBUG"
  - LD_PRELOAD=/usr/lib/libtcmalloc_minimal.so.4 cmake -DWITH_INNOBASE_STORAGE_ENGINE=yes -DCMAKE_BUILD_TYPE=Debug -DWITH_JEMALLOC=yes -DSECURITY_HARDENED=no -DWITH_PIC=no -DCMAKE_CXX_FLAGS_DEBUG="-g -O0" -DCMAKE_C_FLAGS_DEBUG="-g -O0" "${TRAVIS_BUILD_DIR}"
  - LD_PRELOAD=/usr/lib/libtcmalloc_minimal.so.4 make -j $(grep -c processor /proc/cpuinfo)
  - cd ./mysql-test
  - ./mtr --suite=versioning --force --max-test-fail=0
  - cd "${TRAVIS_BUILD_DIR}/RELEASE"
  - LD_PRELOAD=/usr/lib/libtcmalloc_minimal.so.4 cmake -DWITH_INNOBASE_STORAGE_ENGINE=yes -DCMAKE_BUILD_TYPE=Release -DWITH_JEMALLOC=yes -DSECURITY_HARDENED=yes -DWITH_PIC=no -DCMAKE_CXX_FLAGS_DEBUG="-g -O2" -DCMAKE_C_FLAGS_DEBUG="-g -O2" "${TRAVIS_BUILD_DIR}"
  - LD_PRELOAD=/usr/lib/libtcmalloc_minimal.so.4 make -j $(grep -c processor /proc/cpuinfo)
  - cd ./mysql-test
  - ./mtr --suite=versioning --force --max-test-fail=0
```

**Comment by midenok** [comment]
I asked **both** scripts.

**Comment by kevgs** [comment]
Parallel config.

``` yml
# vim ft=yaml
# travis-ci.org definition

branches:
  only:
    - natsys/trunk

# non-container builds don't have enough RAM to reliably compile
sudo: required
dist: trusty

language: cpp
compiler:
  - gcc
#  - clang # See commit f38808 if you want to re-enable clang builds
cache:
  apt:
  ccache:

# Timing on build an test needs to be < 50 minutes. The compile is ~4-5minutes
# so here we group the tests such that this happens.

addons:
  apt:
    packages: # make sure these match debian/control contents
      - bison
      - chrpath
      - cmake
      - debhelper
      - dh-apparmor
      - dpatch
      - libaio-dev
      - libboost-dev
      - libjudy-dev
      - libncurses5-dev
      - libpam0g-dev
      - libreadline-gplv2-dev
      - libssl-dev
      - lsb-release
      - perl
      - po-debconf
      - psmisc
      - zlib1g-dev
      - libcrack2-dev # no effect as the package is disallowed on Travis-CI
      - libjemalloc-dev
      - devscripts # implicit for any build on Ubuntu
      - libtcmalloc-minimal4

env:
  - BUILD_TYPE=-DCMAKE_BUILD_TYPE=Debug -DWITH_JEMALLOC=yes -DSECURITY_HARDENED=no -DWITH_PIC=no -DCMAKE_CXX_FLAGS_DEBUG="-g -O0" -DCMAKE_C_FLAGS_DEBUG="-g -O0" "${TRAVIS_BUILD_DIR}"
  - BUILD_TYPE=-DCMAKE_BUILD_TYPE=Release -DWITH_JEMALLOC=yes -DSECURITY_HARDENED=yes -DWITH_PIC=no -DCMAKE_CXX_FLAGS_DEBUG="-g -O2" -DCMAKE_C_FLAGS_DEBUG="-g -O2" "${TRAVIS_BUILD_DIR}"

script:
  - ${CC} --version ; ${CXX} --version
  - cd "${TRAVIS_BUILD_DIR}"
  - "LD_PRELOAD=/usr/lib/libtcmalloc_minimal.so.4 cmake -DWITH_INNOBASE_STORAGE_ENGINE=yes $BUILD_TYPE && LD_PRELOAD=/usr/lib/libtcmalloc_minimal.so.4 make -j $(grep -c processor /proc/cpuinfo) && cd ./mysql-test && ./mtr --suite=versioning --force --max-test-fail=0"
```
